INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Angela', 'Peña', 'DoctoraVilchez@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Robert', 'Plant', 'Plant.roe@gmail.com', '2018-03-05');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Gustavo', 'Cerati', 'gcc.doe@gmail.com', '2018-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('David', 'Gilmour', 'gilmourD.vlissides@gmail.com', '2018-02-28');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04');
insert into clientes (nombre, apellido, email, create_at) values ('Dominic', 'Marcinkowski', 'dmarcinkowski0@harvard.edu', '2021-12-13');
insert into clientes (nombre, apellido, email, create_at) values ('Gwenneth', 'Wreakes', 'gwreakes1@google.co.uk', '2020-07-07');
insert into clientes (nombre, apellido, email, create_at) values ('Afton', 'Nash', 'anash2@ebay.com', '2020-11-27');
insert into clientes (nombre, apellido, email, create_at) values ('Hildagarde', 'Colgrave', 'hcolgrave3@earthlink.net', '2023-02-16');
insert into clientes (nombre, apellido, email, create_at) values ('Letta', 'Rodie', 'lrodie4@t.co', '2021-11-08');
insert into clientes (nombre, apellido, email, create_at) values ('Tadeo', 'Lewer', 'tlewer5@mozilla.com', '2021-08-21');
insert into clientes (nombre, apellido, email, create_at) values ('Alanna', 'De Morena', 'ademorena6@howstuffworks.com', '2020-12-19');
insert into clientes (nombre, apellido, email, create_at) values ('Norton', 'Chretien', 'nchretien7@macromedia.com', '2021-09-30');
insert into clientes (nombre, apellido, email, create_at) values ('Fiann', 'Skeldon', 'fskeldon8@miibeian.gov.cn', '2020-07-27');
insert into clientes (nombre, apellido, email, create_at) values ('Perl', 'Vatcher', 'pvatcher9@apple.com', '2020-10-27');
insert into clientes (nombre, apellido, email, create_at) values ('Kayley', 'Titterington', 'ktitteringtona@jugem.jp', '2020-07-23');
insert into clientes (nombre, apellido, email, create_at) values ('Eward', 'Udale', 'eudaleb@irs.gov', '2022-11-08');
insert into clientes (nombre, apellido, email, create_at) values ('Andy', 'Thying', 'athyingc@liveinternet.ru', '2021-12-11');
insert into clientes (nombre, apellido, email, create_at) values ('Madeleine', 'Maffei', 'mmaffeid@wikispaces.com', '2021-01-22');
insert into clientes (nombre, apellido, email, create_at) values ('Timothee', 'Weedall', 'tweedalle@sogou.com', '2022-07-04');
insert into clientes (nombre, apellido, email, create_at) values ('Josephine', 'Tredger', 'jtredgerf@ft.com', '2022-08-09');
insert into clientes (nombre, apellido, email, create_at) values ('Maurise', 'Gresser', 'mgresserg@cpanel.net', '2021-01-11');
insert into clientes (nombre, apellido, email, create_at) values ('Winston', 'Soares', 'wsoaresh@weibo.com', '2021-05-03');
insert into clientes (nombre, apellido, email, create_at) values ('Allan', 'Ranyelld', 'aranyelldi@sun.com', '2022-09-11');
insert into clientes (nombre, apellido, email, create_at) values ('Kalie', 'Goforth', 'kgoforthj@cafepress.com', '2020-11-04');
insert into clientes (nombre, apellido, email, create_at) values ('Gloriana', 'Wallentin', 'gwallentink@wisc.edu', '2022-04-23');
insert into clientes (nombre, apellido, email, create_at) values ('Calhoun', 'Pawelec', 'cpawelecl@hexun.com', '2022-02-16');
insert into clientes (nombre, apellido, email, create_at) values ('Kristine', 'Perview', 'kperviewm@altervista.org', '2022-03-11');
insert into clientes (nombre, apellido, email, create_at) values ('Alverta', 'Jiggens', 'ajiggensn@zdnet.com', '2021-10-17');
insert into clientes (nombre, apellido, email, create_at) values ('Delbert', 'Elcoat', 'delcoato@uol.com.br', '2021-02-15');
insert into clientes (nombre, apellido, email, create_at) values ('Humfrid', 'Gyrgorwicx', 'hgyrgorwicxp@sohu.com', '2021-02-11');
insert into clientes (nombre, apellido, email, create_at) values ('Nettie', 'Gatman', 'ngatmanq@prweb.com', '2020-07-20');
insert into clientes (nombre, apellido, email, create_at) values ('Yorker', 'Marke', 'ymarker@theguardian.com', '2020-07-16');
insert into clientes (nombre, apellido, email, create_at) values ('Dorree', 'Rigmand', 'drigmands@slate.com', '2022-02-17');
insert into clientes (nombre, apellido, email, create_at) values ('Glyn', 'Scowcraft', 'gscowcraftt@psu.edu', '2022-06-09');
insert into clientes (nombre, apellido, email, create_at) values ('Brant', 'Eric', 'bericu@discovery.com', '2020-10-18');
insert into clientes (nombre, apellido, email, create_at) values ('Justis', 'Plewman', 'jplewmanv@nsw.gov.au', '2023-02-24');
insert into clientes (nombre, apellido, email, create_at) values ('Avis', 'Waadenburg', 'awaadenburgw@springer.com', '2020-08-27');
insert into clientes (nombre, apellido, email, create_at) values ('Arlin', 'Davidescu', 'adavidescux@google.it', '2022-12-03');
insert into clientes (nombre, apellido, email, create_at) values ('Sidoney', 'Hukins', 'shukinsy@unc.edu', '2022-04-12');
insert into clientes (nombre, apellido, email, create_at) values ('Gwenore', 'Sisson', 'gsissonz@goo.ne.jp', '2020-08-19');
insert into clientes (nombre, apellido, email, create_at) values ('Lion', 'Cubin', 'lcubin10@cornell.edu', '2022-05-13');
insert into clientes (nombre, apellido, email, create_at) values ('Katine', 'Keilloh', 'kkeilloh11@businesswire.com', '2023-04-14');
insert into clientes (nombre, apellido, email, create_at) values ('Bevan', 'Innerstone', 'binnerstone12@ftc.gov', '2021-06-04');
insert into clientes (nombre, apellido, email, create_at) values ('Merlina', 'Jacomb', 'mjacomb13@php.net', '2021-07-18');
insert into clientes (nombre, apellido, email, create_at) values ('Garrard', 'Kiddye', 'gkiddye14@bluehost.com', '2022-06-16');
insert into clientes (nombre, apellido, email, create_at) values ('Vidovic', 'Fairholm', 'vfairholm15@istockphoto.com', '2022-05-14');
insert into clientes (nombre, apellido, email, create_at) values ('Madlin', 'Dailly', 'mdailly16@clickbank.net', '2020-09-26');
insert into clientes (nombre, apellido, email, create_at) values ('Nathaniel', 'Harrington', 'nharrington17@unicef.org', '2020-05-24');
insert into clientes (nombre, apellido, email, create_at) values ('Gracia', 'Pashba', 'gpashba18@foxnews.com', '2021-05-19');
insert into clientes (nombre, apellido, email, create_at) values ('Wilburt', 'Jerschke', 'wjerschke19@woothemes.com', '2022-09-15');
insert into clientes (nombre, apellido, email, create_at) values ('Debra', 'Stanbrooke', 'dstanbrooke1a@elpais.com', '2020-07-12');
insert into clientes (nombre, apellido, email, create_at) values ('Freda', 'Pankethman', 'fpankethman1b@issuu.com', '2023-01-31');
